#!/bin/sh
hash jq || exit 1
[ -d meta ] && [ -d automation ] && [ -d .github/workflows ] || exit 1
ws() { grep -o "[ ]*@$1@" automation/build-package.template.yml | sed "s/@$1@//"; }
targets="$(nix eval --json -f automation/default.nix zigCross --apply builtins.attrNames | jq -r '.[]' | sort | sed "s/^/$(ws targets)- /")"
versions="$(nix eval --json -f automation/default.nix zigVersions --apply builtins.attrNames | jq -r '.[]' | sort -Vr | sed "s/^/$(ws versions)- /")"
export targets versions
awk '{ for (a in ENVIRON) gsub("[ ]*@" _ a _ "@",ENVIRON[a]); print }' < automation/build-package.template.yml > .github/workflows/build-package.yml
