#!/bin/bash
[[ -d meta ]] && [[ -d automation ]] || exit 1

pkgs() {
   for target in "$@"; do
      printf 'processing %s ...\n' "$target" 1>&2
      while read -r pkg; do
         nix-env -qabP --no-name -f src/prebuilt-derive-from.nix --argstr target "$target" -A "$pkg"
      done < automation/prebuilt | jq --raw-input --slurp '{'"\"$target\""': split("\n") | map(select(. != ""))}'
   done
}

gather() {
   while read -r target; do
      if [[ "$target" != *-apple-darwin ]]; then
         pkgs "$target" "$target-static"
      else
         pkgs "$target"
      fi
   done | jq --slurp add
}

cat <<EOF | gather > meta/prebuilt.json
x86_64-apple-darwin
aarch64-apple-darwin
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl
aarch64-unknown-linux-gnu
aarch64-unknown-linux-musl
EOF
