name: build-package

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Zig version'
        required: true
        default: master
        type: choice
        options:
          - master
          - default
          - 0.10.1
          - 0.10.0
          - 0.9.1
          - 0.9.0
          - 0.8.1
          - 0.8.0
      target:
        description: 'Target'
        required: true
        default: all
        type: choice
        options:
          - all

      package:
        description: 'Package to build'
        required: false
        type: string
        default: super-simple

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build package
        run: |
          cd test
          if [[ "$target" == all ]]; then
            if [[ ! "$package" ]]; then
              ./run all_for_version "$version"
            else
              ./run build-package-for-all-targets "$version" "$package"
            fi
          else
            if [[ ! "$package" ]]; then
              ./run all_for_target "$version" "$target"
            else
              ./run build-package "$version" "$target" "$package"
            fi
          fi
        env:
          version: ${{ inputs.version }}
          target: ${{ inputs.target }}
          package: ${{ inputs.package }}
