name: test.nix

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      zig_version:
        description: 'Zig version'
        required: false
        type: string
        default: null
      allow_broken:
        description: 'Do not use the target blacklist'
        required: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build test.nix --argstr zigVersion "${zig_version:-}" --arg allowBroken "${allow_broken:-false}"
        env:
          zig_version: ${{ inputs.zig_version }}
          allow_broken: ${{ inputs.allow_broken }}

