name: update-versions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl https://ziglang.org/download/index.json > versions.json
      - uses: test-room-7/action-update-file@v1.6.0
        with:
          file-path: versions.json
          commit-msg: Update versions.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
