name: update-zig-binaries

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-zig-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl https://ziglang.org/download/index.json > zig-binaries.json
      - uses: test-room-7/action-update-file@v1.6.0
        with:
          file-path: zig-binaries.json
          commit-msg: Update zig-binaries.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
